import { Inter } from "next/font/google";
// import { ChakraProvider } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pared eólica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
      <html lang="en">
          <body className={inter.className}>{children}</body>
      </html>

  );
}
